### ISSUE TITLE
Create register API endpoint that takes in an email, username and passwordand saves it to the database

### ISSUE THREAD

**Issue by kalberry** [emerald-consulting/openbeats#33]
**Task Test**

*Test 1*
1) Open up git bash or terminal if on linux

2) Run the command:
`curl --silent --location --request POST 'http://api.openbeats716.com/api/user/create/' --header 'Content-Type: application/json' --data-raw '{
    "email": "test@email.com",
    "username": "kyletestuser",
    "password": "testpw123"
}'`

3) Confirm that: `{"email": "insert@email.com", "username": "insert@email.com"}` Is returned, or `{"email":["user with this email address already exists."]}` If the user already exists, in which you repeat step 2 using a different email address.

4) Use a database viewer to see that the user was created

**Comment by ethan-richardson** [comment]
Add "Test 1" with italics and  make sure "Task Tests" is bold
