### ISSUE TITLE
As a musical artist with a registered email address and password looking to use Open Beats, I would like to be able to log in to my account using the credentials from my registered email address and password so that I can start using the application.

### ISSUE THREAD

**Issue by RyChrome** [emerald-consulting/openbeats#4]
**Acceptance Test**

*Test 1*
1) In your web browser go to http://www.openbeats716.com/
2) Click "login" in the top right corner
3) Type **dilsy3@gmail.com** in the email field
4) Type **password** in the password
5) Click "Submit"
6) Be directed to a screen with a changed NavBar and feed.

**Comment by focacci** [comment]
Assign me

**Comment by ethan-richardson** [comment]
Provide the client with a specific email and password to log in with for steps 3 & 4.
Link any dependent tasks
